### ISSUE TITLE
Broken area portals? Funny lump size

### ISSUE THREAD

**Issue by julianrombert** [cartman300/Libraria#3]
Many .bsp maps stop working after being loaded and saved with LibrariaLite (without changing the version).

Examples for broken visual data:
1) http://de.ws.q3df.org/map/r7-trilogy-rev/
![grafik](https://user-images.githubusercontent.com/62336892/76960697-42446200-691c-11ea-8911-53a62fae29da.png)
2) http://de.ws.q3df.org/map/r7-xyligan/

On some other maps you get the error "CMOD_LOADSHADERS: FUNNY LUMP SIZE"
Example:
3) http://de.ws.q3df.org/map/kool_boma3/

**Comment by sbarisic** [comment]
Thanks for reporting, i will try to fix the map converter this weekend.

**Comment by julianrombert** [comment]
Thanks a lot, I really appreciate your work!

**Comment by julianrombert** [comment]
If you load and save this map http://de.ws.q3df.org/map/hunterun-20/ with LibrariaLight, the game crashes when loading the map -> Access violation

**Comment by sbarisic** [comment]
You are testing this with the standard Quake 3, and not Quake Live, right?

**Comment by sbarisic** [comment]
Opened up the issue on the bspconv project, i will be moving quake related sources away from this library

https://github.com/sbarisic/bspconv/issues/2
